### ISSUE TITLE
{"error":"Invalid input."}

### ISSUE THREAD

**Issue by clicketyclackety** [mathix420/notion-charts#12]
All the examples on the repo return this value to me when using the latest firefox, chrome or edge on windows 10.

**Comment by mathix420** [comment]
Oh yeah there is an issue, I'm checking that today! Thanks fo reporting this!

**Comment by mathix420** [comment]
This was an issue with the unoficial notion python API, fixed with this PR https://github.com/jamalex/notion-py/pull/294.

Thanks again for reporting the issue!
