### ISSUE TITLE
lost sys.stdin

### ISSUE THREAD

**Issue by mathiasmaul** [mathix420/notion-charts#17]
On a fresh installation on Vercel with the correct token, I’m getting these error messages in the function log:

```
[GET] /notion-schema/[…]/[…]
module initialization error: input(): lost sys.stdin
module initialization error
input(): lost sys.stdin
```

The app returns the error code 500. This happens right after a URL is entered in the `Notion URL` form field, with both your examples and table URLs from the Notion account linked via the token. I’m stumped – do you have any idea what could be happening here?

**Comment by mathix420** [comment]
Hi!
Yes I do think it's an issue with `notion-py` I can't try/test right now but when `notion-py` doesn't get the token correctly it ask for an email an password via `stdin`. And Vercel is just running commands so `stdin` got closed at some point.

I'm going to investigate this more precisely tomorrow morning  (UTC+2).

Have a nice day/evning!

**Comment by mathix420** [comment]
I manage to replicate exactly the same error by deleting the `TOKEN_V2` in my Vercel environment variables

```
module initialization error: input(): lost sys.stdin
module initialization error
input(): lost sys.stdin
```

Here is all the steps you can do to fix this:

1. Go to your vercel dashboard
![image](https://user-images.githubusercontent.com/37625778/118781455-6176b080-b88d-11eb-9e53-4630c2fee621.png)
2. Go to `Settings` tab
![image](https://user-images.githubusercontent.com/37625778/118781578-7fdcac00-b88d-11eb-89c2-cdbda780e492.png)
3. Select `Environment Variables`, if you see exactly this please share me a screen capture of this. If not continue.
![image](https://user-images.githubusercontent.com/37625778/118781978-eb267e00-b88d-11eb-8a4e-184083546f38.png)
4. Add `TOKEN_V2` (case sensitive!)
![image](https://user-images.githubusercontent.com/37625778/118782204-2759de80-b88e-11eb-9ad3-70357434e767.png)
   - To get the value, got on [notion.so](https://notion.so), inspect the element (or press F12).
   - Go to the `Application` tab.
   - Click on the `Cookies` section.
   - Find the `token_v2` row and copy it's value (it should be some long hexadecimal string).
   - Paste it in the `VALUE` section in vercel.
   - Then click `ADD` (in vercel again)
5. Now we need to redeploy your `notion-charts` for changes to take effect.
   - Go to `Deployments`.
   - Click the latest one.
   ![image](https://user-images.githubusercontent.com/37625778/118783004-f037fd00-b88e-11eb-9ed9-e15870aec41d.png)
   - Click on the 3 vertical dots.
   - And click `Redeploy`
   - Wait for it to finish, go to your `notion-charts` endpoint (do not forget to refresh). And try to use it.

All that should fix your issue, please tell me if anything else append, or if it does not fix the issue!

**Comment by mathiasmaul** [comment]
Fixed; thank you so much for the quick reply!

**Comment by mathix420** [comment]
Glad it fixed the issue! Have a nice day!
