### ISSUE TITLE
Feature request: Automatic dark mode [prefers-color-scheme]

### ISSUE THREAD

**Issue by jamesdwilson** [mathix420/notion-charts#19]
Could you implement an automatic dark mode, based on the css media query like this?

https://fjolt.com/article/css-auto-dark-mode

Thanks in advance

**Comment by mathix420** [comment]
Hi, thanks for this feature request!

I don't think this will be possible via CSS, as google charts colors need to be configured via JS.
That could be done with the client-hint `Sec-CH-Prefers-Color-Scheme`.

I'm pretty busy right now, so feel free to create a PR on this!

**Comment by mathix420** [comment]
Done in https://github.com/mathix420/notion-charts/commit/5c99c0756986ec244a050488a91f779c6e124225!
Hope it fixes this issue, if not, please let me know.

Have a nice day!
