### ISSUE TITLE
build on vercel failed: pip3

### ISSUE THREAD

**Issue by hellomarb** [mathix420/notion-charts#5]
Sadly the build failed on vercel for me with the following message:

`Error: Command failed: pip3 install --disable-pip-version-check --target . --upgrade -r /vercel/6c259a13/requirements.txt`

Have you an idea what's the problem with that?

**Comment by mathix420** [comment]
Hi, can you give me more informations about this error ?

Can you go into the `deployments` tab on your `notion-charts` project in Vercel then click on the failed deployment, then you can copy full `Build logs`. Please add this log to this thread so I can help you

**Comment by hellomarb** [comment]
Here the complete log:

`15:16:47.405  Retrieving list of deployment files...
15:16:47.646  Downloading 8 deployment files...
15:16:49.497  Installing build runtime...
15:16:50.805  Build runtime installed: 1307.972ms
15:16:51.128  Looking up build cache...
15:16:51.318  Build cache not found
15:16:51.640  Installing required dependencies...
15:16:53.123  Failed to run "pip install --disable-pip-version-check --target . --upgrade -r /vercel/6c259a13/requirements.txt"...
15:16:53.125  Error: Command failed: pip3 install --disable-pip-version-check --target . --upgrade -r /vercel/6c259a13/requirements.txt
15:16:53.125    Running command git clone -q git://github.com/mathix420/notion-py.git /tmp/pip-req-build-2v51j5hb
15:16:53.125      ERROR: Command errored out with exit status 1:
15:16:53.125       command: /usr/local/bin/python3.6 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-2v51j5hb/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-2v51j5hb/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-pn03xw_f
15:16:53.125           cwd: /tmp/pip-req-build-2v51j5hb/
15:16:53.125      Complete output (7 lines):
15:16:53.125      Traceback (most recent call last):
15:16:53.125        File "<string>", line 1, in <module>
15:16:53.125        File "/tmp/pip-req-build-2v51j5hb/setup.py", line 12, in <module>
15:16:53.125          install_requires = [str(ir.req) for ir in reqs]
15:16:53.125        File "/tmp/pip-req-build-2v51j5hb/setup.py", line 12, in <listcomp>
15:16:53.126          install_requires = [str(ir.req) for ir in reqs]
15:16:53.126      AttributeError: 'ParsedRequirement' object has no attribute 'req'
15:16:53.126      ----------------------------------------
15:16:53.126  ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
15:16:53.126  Collecting git+git://github.com/mathix420/notion-py.git (from -r /vercel/6c259a13/requirements.txt (line 1))
15:16:53.126    Cloning git://github.com/mathix420/notion-py.git to /tmp/pip-req-build-2v51j5hb
15:16:53.126      at makeError (/vercel/a4ea44d4c368cf29/.build-utils/.builder/node_modules/@now/python/dist/index.js:3665:9)
15:16:53.126      at /vercel/a4ea44d4c368cf29/.build-utils/.builder/node_modules/@now/python/dist/index.js:3769:16
15:16:53.126      at processTicksAndRejections (internal/process/task_queues.js:97:5)
15:16:53.126      at async pipInstall (/vercel/a4ea44d4c368cf29/.build-utils/.builder/node_modules/@now/python/dist/index.js:334:9)
15:16:53.126      at async Object.installRequirementsFile (/vercel/a4ea44d4c368cf29/.build-utils/.builder/node_modules/@now/python/dist/index.js:364:5)
15:16:53.126      at async Object.module.exports.178.exports.build (/vercel/a4ea44d4c368cf29/.build-utils/.builder/node_modules/@now/python/dist/index.js:719:9)
15:16:53.126      at async buildStep (/var/task/sandbox-worker.js:20410:20)
15:16:53.126      at async mainSub (/var/task/sandbox-worker.js:20146:9)
15:16:53.126      at async main (/var/task/sandbox-worker.js:20023:5) {
15:16:53.126    code: 1,
15:16:53.126    stdout: 'Collecting git+git://github.com/mathix420/notion-py.git (from -r /vercel/6c259a13/requirements.txt (line 1))\n' +
15:16:53.126      '  Cloning git://github.com/mathix420/notion-py.git to /tmp/pip-req-build-2v51j5hb\n',
15:16:53.126    stderr: '  Running command git clone -q git://github.com/mathix420/notion-py.git /tmp/pip-req-build-2v51j5hb\n' +
15:16:53.126      '    ERROR: Command errored out with exit status 1:\n' +
15:16:53.126      `     command: /usr/local/bin/python3.6 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-2v51j5hb/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-2v51j5hb/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\\r\\n'"'"', '"'"'\\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-pn03xw_f\n` +
15:16:53.127      '         cwd: /tmp/pip-req-build-2v51j5hb/\n' +
15:16:53.127      '    Complete output (7 lines):\n' +
15:16:53.127      '    Traceback (most recent call last):\n' +
15:16:53.127      '      File "<string>", line 1, in <module>\n' +
15:16:53.127      '      File "/tmp/pip-req-build-2v51j5hb/setup.py", line 12, in <module>\n' +
15:16:53.127      '        install_requires = [str(ir.req) for ir in reqs]\n' +
15:16:53.127      '      File "/tmp/pip-req-build-2v51j5hb/setup.py", line 12, in <listcomp>\n' +
15:16:53.127      '        install_requires = [str(ir.req) for ir in reqs]\n' +
15:16:53.127      "    AttributeError: 'ParsedRequirement' object has no attribute 'req'\n" +
15:16:53.127      '    ----------------------------------------\n' +
15:16:53.127      'ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.\n',
15:16:53.127    failed: true,
15:16:53.127    signal: null,
15:16:53.127    cmd: 'pip3 install --disable-pip-version-check --target . --upgrade -r /vercel/6c259a13/requirements.txt',
15:16:53.127    timedOut: false,
15:16:53.127    killed: false
15:16:53.127  }
15:16:55.013  Done with "main.py"`

**Comment by mathix420** [comment]
I really do not have an idea, but for me it's working perfectly fine. Maybe that's just a random error from Vercel. Have you tried to run the stack one more time ?

**Comment by hellomarb** [comment]
I tried it with a new deployment to vercel, same result.
Perhaps new accounts get a new environment?

The main error is this part:
`Error: Command failed: pip3 install --disable-pip-version-check --target . --upgrade -r /vercel/729a3f5e/requirements.txt`

**Comment by mathix420** [comment]
Ok I'm going to investigate this more deeply

**Comment by mathix420** [comment]
It should work now, that was a bug with `notion-py` fixed here https://github.com/mathix420/notion-py/commit/fc10c38090857034facd6159b6469c9fb6763129

Thanks for reporting this issue !
