### ISSUE TITLE
Internal server error

### ISSUE THREAD

**Issue by jwvanderbeck** [mathix420/notion-charts#8]
Tried this out today using the `https://notion-charts.now.sh` URL and pasting in my Notion page which has a database on it, but it just returned an Internal Server Error.

**Comment by mathix420** [comment]
Hi @jwvanderbeck thanks for reporting this issue!
Is your notion page public?

**Comment by jwvanderbeck** [comment]
Get the same error if I deploy my own copy to Vercel.

**Comment by jwvanderbeck** [comment]
> Hi @jwvanderbeck thanks for reporting this issue!
> Is your notion page public?

To be honest I am not sure? I never explicitly made it public or private so it is whatever the default it.  I tried deploying to vercel and providing my `token_v2` but got the same result.

**Comment by mathix420** [comment]
As I can see on my side `8253daffa66845c59dc9d99cf999400c` this notion ID isn't public. So for `https://notion-charts.now.sh` that was the issue.

But this should not happen if you are using your `token_v2`, can you give me a screen shot or dump of these logs? [How to do it](https://vercel.com/knowledge/where-are-vercel-logs)

**Comment by jwvanderbeck** [comment]
I clicked Share and then Share to Web, and tried again.  Now instead of a server error I see Not Found in both cases.

Not seeing anything show up under Function logs when I access my deployed version.

**Comment by mathix420** [comment]
@jwvanderbeck I investigate this, I tell you back

**Comment by mathix420** [comment]
@jwvanderbeck I have updated the unoffical Notion API, maybe now it can work (if you try on `https://notion-charts.now.sh` with your page accessible in public).
If it work you'll need to redeploy your Vercel copy to get these changes.

**Comment by mathix420** [comment]
Hi @jwvanderbeck, I have found why Notion Charts isn't working fine.
I suggest you to use the new version on your private Vercel deployment.
Please tell me is that fixed the issue

**Comment by jwvanderbeck** [comment]
I still seem to have the "Not Found" error posted above, though is looks slightly different now.
`{"error":"404 Not Found: No status found in the response."}`

**Comment by jwvanderbeck** [comment]
I do get some log text now, which I didn't before:
![image](https://user-images.githubusercontent.com/161126/97595515-fdf46680-19c0-11eb-9ccd-174543c1ad63.png)

**Comment by mathix420** [comment]
Okay, this error happen beacause this tool is meant to display pies charts. And by default it uses `Not Started` `In Progress` and `Done` in a notion databases. If you wish using other fields you can follow the documentation on [the readme](/README.md).

**Comment by jwvanderbeck** [comment]
Ahh my apologies.  I did not notice that it was for pie charts only :(

**Comment by mathix420** [comment]
No worries I think I'm going to add multiple other charts type to this tool 😉
